apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: envelope-game
  annotations:
    github.com/project-slug: liatrio/envelope-game
spec:
  type: other
  lifecycle: unknown
  owner: Liatrio
