version: '3.8'
services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    working_dir: /home/node/app
    environment: 
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes: 
      - ./:/home/node/app/
    expose:
      - "8080"
    ports:
      - "3000:3000"
    restart: always
  db:
    build:
      context: ./docker/sql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
