version: '3.8'
services:
  node:
    image: node:14
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /home/node/app
    environment: 
      - NODE_ENV=development
    volumes: 
      - ./:/home/node/app/
    expose:
      - "8080"
    ports:
      - "3000:3000"
    command: "npm start"
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=envelope-game
    volumes: 
      - ./initdb/:/docker-entrypoint-initdb.d/
volumes:
  game-data:
