version: '3.8'
services:
  node:
    image: node:14
    working_dir: /home/node/app
    environment: 
      - NODE_ENV=development
    volumes: 
      - ./:/home/node/app/
    expose:
      - "8080"
    ports:
      - "3000:3000"
    command: "npm start"
