{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}"
spec:
  hosts:
  - {{ .Values.istio.host }}
  gateways:
  - {{ .Values.istio.gateway.name }}
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ include "envelope-game.fullname" . }}
        port:
          number: {{ .Values.service.port }}
---
{{ if .Values.istio.gateway.create }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.istio.host }}
{{ end }}
{{ end }}
