name: Release

on:
  push:
    branches:
      - main
    paths:
      - "**/charts/*"
      - ".github/workflows/release.yml"
      - "lib/*.js"
      - "react/*.js"
      - "routes/*.js"
      - ".releaserc.yaml"
  workflow_dispatch: {}

concurrency:
  group: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        id: release
        uses: liatrio/github-actions/conventional-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
